[package]
name = "stak-minifier-macro"
description = "Macros to minify Stak Scheme source codes"
version = "0.1.1"
edition.workspace = true
keywords.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0.79", features = ["proc-macro"] }
quote = "1.0.35"
syn = "2.0.58"
stak-minifier = { version = "0.1.1", path = "../minifier" }
stak-macro-util = { version = "0.1.0", path = "../macro-util" }

[lints]
workspace = true
