[package]
name = "stak-compile"
description = "Stak Scheme bytecode compiler"
version = "0.1.62"
edition.workspace = true
keywords.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true

[features]
default = ["float"]
float = ["stak-sac/float"]

[dependencies]
stak-sac = { version = "0.1", path = "../../sac", features = ["std"] }

[lints]
workspace = true
