[package]
name = "stak-minify"
description = "Stak Scheme source code minifier"
version = "0.1.36"
edition.workspace = true
keywords.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true

[features]
default = ["float"]
float = ["stak-sac/float"]

[dependencies]
stak-sac = { version = "0.1.60", path = "../../sac", features = ["std"] }

[lints]
workspace = true
