[package]
name = "stak-decode"
version.workspace = true
edition.workspace = true
description = "Stak Scheme bytecode decoder"
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
stak-sac = { path = "../../sac", version = "0.12.9", features = [
  "float",
  "std",
] }

[lints]
workspace = true
