[package]
name = "stak-decode"
version.workspace = true
edition.workspace = true
description = "Stak Scheme bytecode decoder"
readme.workspace = true
repository.workspace = true
license-file.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
stak-sac = { version = "0.10.34", features = [
  "float",
  "std",
], path = "../../sac" }

[lints]
workspace = true
