[package]
name = "stak-decode"
description = "Stak Scheme bytecode decoder"
version = "0.1.75"
edition.workspace = true
keywords.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
stak-sac = { version = "0.1.73", path = "../../sac", features = [
  "float",
  "std",
] }

[lints]
workspace = true
