[package]
name = "no-std-no-alloc"
version.workspace = true
edition.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
publish = false

[dependencies]
heapless = "0.9.2"
stak = { path = "../../root", version = "0.12.10", default-features = false }

[build-dependencies]
stak-build = { path = "../../build", version = "0.12.10" }

[lints]
workspace = true
