[package]
name = "stak-minifier"
description = "Stak Scheme source code minifier"
version = "0.1.53"
edition.workspace = true
keywords.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
stak-configuration = { version = "0.1.71", path = "../configuration" }
stak-device = { version = "0.2.75", path = "../device", features = ["std"] }
stak-file = { version = "0.4.33", path = "../file" }
stak-macro = { version = "0.1.76", path = "../macro" }
stak-r7rs = { version = "0.8.10", path = "../r7rs" }
stak-process-context = { version = "0.2.33", path = "../process_context" }
stak-vm = { version = "0.7.4", path = "../vm" }
stak-time = { version = "0.1.16", path = "../time" }

[dev-dependencies]
pretty_assertions = "1.4.1"

[lints]
workspace = true
