[package]
name = "stak-minifier"
description = "Stak Scheme source code minifier"
version = "0.1.44"
edition.workspace = true
keywords.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
stak-configuration = { version = "0.1.62", path = "../configuration" }
stak-device = { version = "0.2.66", path = "../device", features = ["std"] }
stak-file = { version = "0.4.24", path = "../file" }
stak-macro = { version = "0.1.67", path = "../macro" }
stak-r7rs = { version = "0.8.1", path = "../r7rs" }
stak-process-context = { version = "0.2.24", path = "../process_context" }
stak-vm = { version = "0.6.1", path = "../vm" }
stak-time = { version = "0.1.7", path = "../time" }

[dev-dependencies]
pretty_assertions = "1.4.1"

[lints]
workspace = true
