[package]
name = "stak-repl"
version.workspace = true
edition.workspace = true
description = "Stak Scheme REPL"
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
stak-sac = { path = "../../sac", version = "0.11.14", features = ["std"] }

[features]
default = ["float"]
float = ["stak-sac/float"]

[lints]
workspace = true
