[package]
name = "stak-util"
version.workspace = true
edition.workspace = true
description = "Stak Scheme utilities"
readme.workspace = true
repository.workspace = true
license-file.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
cfg-elif = "0.6.3"
noop-executor = "0.1.0"

[lints]
workspace = true
