[package]
name = "stak-lzss-fuzz"
version.workspace = true
edition.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[package.metadata]
cargo-fuzz = true

[[bin]]
bench = false
doc = false
name = "main"
path = "fuzz_targets/main.rs"
test = false

[dependencies]
libfuzzer-sys = "0.4.10"
stak-lzss = { path = ".." }
