[package]
name = "stak-native"
description = "Optimized primitives of native functions for Stak Scheme"
version = "0.2.1"
edition.workspace = true
keywords.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
stak-vm = { version = "0.7.23", path = "../vm" }

[lints]
workspace = true
