[package]
name = "stak-process-context"
description = "Process context for Stak Scheme"
version = "0.2.26"
edition.workspace = true
keywords.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true

[features]
libc = []
std = []

[lints]
workspace = true

[dependencies]
stak-vm = { version = "0.6.3", path = "../vm" }
