[package]
name = "embedded-script"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
any-fn = "0.6.3"
rand = "0.9.2"
stak = { path = "../../root", version = "0.11.14" }

[build-dependencies]
stak-build = { path = "../../build", version = "0.11.14" }

[lints]
workspace = true
