[package]
name = "custom-vm"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
stak = { path = "../../root", version = "0.12.9" }

[build-dependencies]
stak-build = { path = "../../build", version = "0.12.9" }

[lints]
workspace = true
