[package]
name = "stak-macro-util"
version.workspace = true
edition.workspace = true
description = "Macro utilities for Stak Scheme"
readme.workspace = true
repository.workspace = true
license-file.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
proc-macro2 = "1.0.97"
quote = "1.0.40"
syn = "2.0.105"

[lints]
workspace = true
