[package]
name = "stak-macro-util"
description = "Macro utilities for Stak Scheme"
version = "0.1.30"
edition.workspace = true
keywords.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = "2.0.76"

[lints]
workspace = true
